### ISSUE TITLE
✨ 사장님 앱 로그인 구현

### ISSUE THREAD

**Issue by zer0who** [Team-JubJub/ZupZup_backend#100]
## 💬 Description
사장님 앱의 단순한 로그인 기능을 구현합니다.
기능: 아이디, 비밀번호 입력 -> 서버에서 validation, 맞으면 가게의 pk값 리턴

## 📝 Todo
- [x] 사장님 앱 로그인 controller 구현
- [x] 사장님 앱 로그인 service 구현
- [x] 비밀번호 해시함수 적용하기
- [x] 테스트(로컬 혹은 테스트 서버)
- [x] 테스트 서버 배포
- [x] 운영 서버 배포
