### ISSUE TITLE
🛠️ [FIX] 사용자 앱 - Auth의 request body 중 잘못된 값을 포함한 요청에 대한 validation

### ISSUE THREAD

**Issue by zer0who** [Team-JubJub/ZupZup_backend#102]
## 💬 Description
사용자 앱의 Auth 요청 중 request body에 잘못된 값이 포함된 요청에 대한 예외처리를 추가합니다.

## 📝 Todo
- [x] 닉네임 - 4bytes - 12bytes(EUC-KR, CP-949 기준) 사이의 값이 아닌 닉네임에 대한 예외처리
- [x] 회원가입 - 플랫폼 유니크 id, 이름, 닉네임, 휴대폰 번호, 성별, 약관(필수, 선택) 동의 여부의 값에 대한 예외처리
- [x] 로그인(모든 토큰 만료 시) - 플랫폼 유니크 id 값에 대한 예외처리
- [x] 내 계정 찾기 - 전화번호의 값에 대한 예외처리
