### ISSUE TITLE
🛠️[FIX] 회원탈퇴 수정

### ISSUE THREAD

**Issue by zer0who** [Team-JubJub/ZupZup_backend#107]
## 💬 Description
회원탈퇴의 path에 prath variable로 provider parameter를 추가하고, 애플일 경우 client secret(jwt)을 생성하는 로직을 추가합니다.

## 📝 Todo
- [x] path variable추가
- [x] service layer에서 apple일 경우 분기 처리, client secret 생성 로직 추가
- [x] JwtTokenProvider에 client secret 생성 메서드 추가
- [x] 명세 수정(바뀐 부분 추가)
- [x] Local에서 test
- [x] Test server에 올리기
