### ISSUE TITLE
🛠️ [FIX] 도메인 수정(temp)

### ISSUE THREAD

**Issue by zer0who** [Team-JubJub/ZupZup_backend#123]
## 💬 Description
테이블 이름 등에 관련한 자잘한 수정이 이루어집니다.

## 📝 Todo
- [x] 테이블 명 정리 - 복수로 통일(user가 불가해 users로 사용 중인데, 이게 복수이기 때문에 이걸로 통일)
- [x] 컬럼 명 정리
- [x] 컬럼과 관련한 데이터 타입 정리
- [x] 유저 데이터에 가입한 시간 추가
