### ISSUE TITLE
🛠️ [FIX] 사장님 Entity Auth, Store 분리

### ISSUE THREAD

**Issue by zer0who** [Team-JubJub/ZupZup_backend#127]
## 💬 Description
사장님 Entity(기존 Store)를 Auth 파트와 Store 파트로 분리합니다. 이는 후의 서비스에서 한 사장님이 여러 가게를 가질 경우 등을 대비한 설계 변경입니다. 회의 후 이를 진행할지 말지 결정할 것이지만 우선 이슈는 오픈해두고 코드 변경을 진행해놓도록 하겠습니다.

## 📝 Todo
- [x] 사장님 Auth Entity 생성
- [x] Store entity에서 login ID, login password를 사장님 Auth Entity로 이동
- [x] Store entity에 외래키로 사장님 Auth Entity의 PK를 등록
