### ISSUE TITLE
🛠️ [FIX] 신규 주문의 주문 취소, 확정 수정

### ISSUE THREAD

**Issue by zer0who** [Team-JubJub/ZupZup_backend#137]
## 💬 Description
신규 주문의 주문 취소와 확정에 대한 수정을 수행합니다. 이전에 만들어뒀던 코드의 분리, 로직 보완 및 수정, url 매핑 정도가 수정될 예정입니다.

## 📝 Todo
- [x] 이전에 만들었던 코드에서 신규 주문에 대한 로직 분리
- [x] 주문 취소, 확정(update(patch)) service 로직 정리 및 보완
- [x] 신규 주문에 대한 url 매핑, controller 설계 및 생성
