### ISSUE TITLE
🛠️ [FIX] 확정된 주문의 주문 취소, 완료 수정

### ISSUE THREAD

**Issue by zer0who** [Team-JubJub/ZupZup_backend#138]
## 💬 Description
이전에 생성해뒀던 주문 처리 로직에서 확정된 주문의 주문 취소, 완료 기능을 분리하여 정리 및 보완합니다. 더불어 url 매핑도 달라질 예정입니다.

## 📝 Todo
- [x] 이전에 생성했던 주문 처리 로직에서 확정 주문에 대한 로직 분리
- [x] 주문 취소, 완료(update(patch)) service 로직 정리 및 보완
- [x] 확정 주문에 대한 url 매핑, controller 설계 및 생성
