### ISSUE TITLE
✨사장님 앱 security 작업

### ISSUE THREAD

**Issue by zer0who** [Team-JubJub/ZupZup_backend#145]
## 💬 Description
사장님 앱에 security를 설정합니다.

## 📝 Todo
- [x] 사장님 앱 security config 수정
- [x] 사장님 앱 jwt 관련 코드 작성
- [x] 사장님 앱 controller에 security 관련 parameter 설정
