### ISSUE TITLE
🛠️ [FIX] dto static 제한자 제거

### ISSUE THREAD

**Issue by zer0who** [Team-JubJub/ZupZup_backend#165]
## 💬 Description
dto 내부클래스들의 static 제한자를 삭제합니다. 이는 서버 프로그램 로드 시 메모리에 클래스 정보가 바로 로드되어 메모리가 낭비되는 것을 방지하기 위함입니다.
+ 08/02 내용 추가
static 접근 제한자를 뺐더니, request 관련해서 이슈가 생기는 것을 발견했습니다. 이와 관련해서 이슈 항목을 추가하고 코드 수정하도록 하겠습니다. 자세한 내용은 PR때 작성하도록 하겠습니다.

## 📝 Todo
- [x] Seller 파트의 dto 내부 클래스들 static 제한자 제거
- [x] Customer 파트의 dto 내부 클래스들 static 제한자 제거
------- 추가분 -------
- [x] Seller 파트의 inner class형태인 dto들 모두 분리
- [x] Customer 파트의 inner class형태인 dto들 모두 분리
