### ISSUE TITLE
✨사용자 앱 - 닉네임 수정 API 구현

### ISSUE THREAD

**Issue by zer0who** [Team-JubJub/ZupZup_backend#167]
## 💬 Description
사용자 앱의 닉네임 수정 API를 구현합니다.

## 📝 Todo
- [x] 닉네임 수정 Controller 구현
- [x] 닉네임 수정 Service 구현
- [x] 닉네임 수정 dto 구현
- [x] API 명세
