### ISSUE TITLE
🛠️ [Fix]프로젝트 구조 재변경

### ISSUE THREAD

**Issue by zer0who** [Team-JubJub/ZupZup_backend#19]
## 💬 Description
이전에 변경했던 구조보다 더 괜찮은 설계구조를 알게되어 변경하고자 합니다.

## 📝 Todo
- [x] Gradle(using IntelliJ)에서의 구조 변경을 위한 설정 방법 공부
- [x] 프로젝트 구조를 알게 된 구조로의 변경
- [x] 원래의 모듈 및 클래스들 변경된 구조에서 각자 위치로의 이동
