### ISSUE TITLE
🛠️ [FIX] 사용자 앱 - 가게 관련 기능 security 적용

### ISSUE THREAD

**Issue by zer0who** [Team-JubJub/ZupZup_backend#191]
## 💬 Description
사용자 앱의 가게 관련 기능에 security를 적용합니다.

## 📝 Todo
- [x] Store - 카테고리별 GET security 적용
- [x] Store - 단건 GET security 적용
- [x]  Store - 찜한 가게 GET security 적용
