### ISSUE TITLE
🛠️ [FIX] 사장님 앱 - 가게, 아이템 관련 api 에러 핸들링 및 스웨거 명세 상세화

### ISSUE THREAD

**Issue by zer0who** [Team-JubJub/ZupZup_backend#199]
## 💬 Description
사장님앱의 가게, 아이템 관련 파트에서 필요한 에러 핸들링을 수행합니다. 그리고 스웨거에 표시될 명세를 상세화 합니다.

## 📝 Todo
- [x] 가게 파트 - 가게 전체 조회 예외 처리
- [x] 가게 파트 - 영업, 휴무 설정 예외 처리
- [x] 가게 파트 - 공지 수정 예외 처리
- [x] 가게 파트 - 공지 제외 수정 예외 처리
- [x] 상품 파트 - 아이템 저장 예외 처리
- [x] 상품 파트 - 아이템 업데이트 예외 처리
- [x] 상품 파트 - 아이템 삭제 예외 처리
- [x] 상품 파트 - 아이템 전체 읽어오기 예외 처리
- [x] 상품 파트 - 아이템 갯수 수정 예외 처리
- [x] 주문 파트 스웨거 명세 상세화
- [x] 가게 파트 스웨거 명세 상세화
- [x] 상품 파트 스웨거 명세 상세화
- [x] 전체 상태코드 테스트
