### ISSUE TITLE
🛠️ [FIX] Entity 수정 - Stores

### ISSUE THREAD

**Issue by zer0who** [Team-JubJub/ZupZup_backend#204]
## 💬 Description
확정된 기능에 적용되도록 사장님 앱과 사용자 앱에 사용되는 Entity 중 Stores entity를 수정합니다.

## 📝 Todo
- [x] 대표자 이름 추가
- [x] 대표자 연락처 추가
- [x] 기존 contact -> storeContact(가게 연락처)로 수정
- [x] 사업자 등록번호 추가
- [x] 찜한 사용자(List<사용자Id>) 추가
- [x] 프로모션 추가
- [x] 관련 dto 수정
- [x] 관련 로직 수정
