### ISSUE TITLE
🛠️ [FIX] Entity 수정 - Users

### ISSUE THREAD

**Issue by zer0who** [Team-JubJub/ZupZup_backend#205]
## 💬 Description
확정된 기능에 적용되도록 사장님 앱과 사용자 앱에 사용되는 Entity 중 Users entity를 수정합니다.

## 📝 Todo
- [x] 찜한 가게 추가
- [x] 관련 dto 수정
- [x] 관련 로직 수정
