### ISSUE TITLE
🛠️ ✨  [FIX & NEW] 사용자 앱 - 가게 조회 API 수정, 구현

### ISSUE THREAD

**Issue by zer0who** [Team-JubJub/ZupZup_backend#214]
## 💬 Description
사용자 앱에서 가게를 조회하는 기능에 대한 API를 구현합니다.

## 📝 Todo
- [x] url 설계
- [x] 가게 카테고리별 GET 구현
- [x] 가게 단건 GET 구현
- [x] 찜한 가게 GET 구현
- [x] 예외 처리
