### ISSUE TITLE
🛠️ [FIX] Users entity 수정 - FCM device token 추가

### ISSUE THREAD

**Issue by zer0who** [Team-JubJub/ZupZup_backend#217]
## 💬 Description
푸시 알림을 위한 FCM 연동에 있어 사용자 별 device token이 필요하여 테이블에 deviceToken 컬럼을 추가합니다.
그와 더불어 알림 설정을 한 가게 컬럼을 추가합니다.

## 📝 Todo
- [x] Users entity - deviceToken 추가
- [x] Users entity - alertStores 추가
- [x] 회원가입 시 deviceToken 받아오는 로직 추가
