### ISSUE TITLE
🛠️ [FIX] 사용자 앱 명세 및 dto 수정

### ISSUE THREAD

**Issue by zer0who** [Team-JubJub/ZupZup_backend#223]
## 💬 Description
사용자 앱의 명세와 세세한 dto 수정을 수행합니다.

## 📝 Todo
+ 카테고리별 가게 조회
- [x] 배열 형태로 명세 수정
- [x] isOpen 지금 type String으로 명세 된 부분 boolean으로 수정
- [x] 위치 정보 추가
- [x] 카테고리 enum type 생성(값 대문자)
+ 가게 상세 조회
- [x] response에 찜 여부, 알림 설정 여부 추가
+ 유저의 주문 요청
- [x] response에 매장 전화번호 추가
+ 주문 조회
- [x] 배열 형태로 명세 수정
- [x] response에 orderTime 추가
