### ISSUE TITLE
🛠️ [FIX] 가게 Entity - 등록 상태 컬럼 추가

### ISSUE THREAD

**Issue by zer0who** [Team-JubJub/ZupZup_backend#227]
## 💬 Description
가게 entity의 등록 상태 컬럼을 추가합니다.
해당 컬럼은 NEW, WAIT, CONFIRM의 세 가지 enum값을 가집니다.

## 📝 Todo
- [x] Enum Enterstate 추가
- [x] Stores table에 enterState 추가(enum type)
- [x] 사장님 앱 관련 로직 수정(NEW 상태인 가게 접근 불가)
- [x] 사용자 앱 관련 로직 수정(NEW, WAIT 상태인 가게 접근 불가)
