### ISSUE TITLE
✨사용자 APP - Order part(POST, GET(전체))

### ISSUE THREAD

**Issue by zer0who** [Team-JubJub/ZupZup_backend#23]
## 💬 Description
고객님 APP의 order part, POST 부분을 구현할 예정입니다.

## 📝 Todo
- [x] 기존 order entity를 이용한 개발이 가능할지 테스트
- [x] 테스트 완료시 고객님 기준 ordre status, 사장님 기준 order status 다른 부분에 대한 구현 방법 생각
- [x] url 결정
- [x] POST 구현
- [x] 주문 목록 GET 구현
