### ISSUE TITLE
🛠️ [FIX] 사용자 앱 - dto 수정

### ISSUE THREAD

**Issue by zer0who** [Team-JubJub/ZupZup_backend#230]
## 💬 Description
사용자 앱의 dto를 수정합니다.

## 📝 Todo
- [x] device token 받는 파트 -> sign up에서 sign in으로 수정
- [x] store 전체 get에 item list 추가(최대 할인율을 show를 위함)
- [x] 주문 전체 get에 visit time 추가
- [x] 찜, 알림 설정 시 set -> true, unset -> false 리턴하게 수정
