### ISSUE TITLE
🛠️ [FIX] stores, users entity의 찜, 알림 관련 컬럼 타입 Set으로 변경

### ISSUE THREAD

**Issue by zer0who** [Team-JubJub/ZupZup_backend#238]
## 💬 Description
stores, users entity의 찜, 알림 관련 컬럼의 타입을 Set으로 변경합니다.

## 📝 Todo
- [x] Users entity 찜, 알림 컬럼 Set으로 수정
- [x] Stores entity 찜, 알림 컬럼 Set으로 수정
- [x] 관련 로직의 타입 수정
