### ISSUE TITLE
🛠️ [FIX] 사용자 앱 - 애플 회원가입, 회원탈퇴 로직 수정

### ISSUE THREAD

**Issue by zer0who** [Team-JubJub/ZupZup_backend#246]
## 💬 Description
애플 계정의 회원가입, 탈퇴 로직을 수정합니다.

## 📝 Todo
- [x] getRefreshToken API 생성
- [x] 애플 회원탈퇴 파라미터 authCode -> refreshToken으로 변경
- [x] 회원탈퇴 시 애플 회원탈퇴를 분리
