### ISSUE TITLE
✨ 첫 주문 데이터 저장

### ISSUE THREAD

**Issue by zer0who** [Team-JubJub/ZupZup_backend#248]
## 💬 Description
유저가 첫 주문을 할 경우, 첫 주문 테이블에 저장하기 위한 로직을 추가합니다.

## 📝 Todo
- [x] 첫 주문 entity에 builder 추가
- [x] 첫 주문의 repository 생성
- [x] 사용자 주문하기에 첫 주문 여부 판단, 저장하기 로직 추가
