### ISSUE TITLE
🛠️ [FIX] 사용자 탈퇴 시 주문 제어

### ISSUE THREAD

**Issue by zer0who** [Team-JubJub/ZupZup_backend#249]
## 💬 Description
사용자가 탈퇴할 시 해당 사용자가 했던 주문의 제어 로직을 정합니다.

## 📝 Todo
- [x] 회의 때 안건내고 status로 제어할지, 컬럼(isDeleted) 추가로 제어할지 정하기 -> OrderStatus에 상태 추가로 결정
- [x] 사용자 회원 탈퇴시 사용자의 주문 상태 업데이트하기
- [x] 주문 전체 GET(사장님, 회원 모두)에 filter 적용(상태 WITHDREW는 필터링하고 건네주기)
