### ISSUE TITLE
🛠️[Fix] OrderStatus 하나로 합치기

### ISSUE THREAD

**Issue by zer0who** [Team-JubJub/ZupZup_backend#26]
## 💬 Description
orderStatus를 figma를 참고해서 만들다보니 사용자 앱에서 "대기" 상태, 사장님 앱에서 "신규" 상태를 서버단에서 처리해서 넘겨줘야하는 줄 알고 따로 분리해뒀었습니다. 어제 클라이언트와 회의 중 해당 내용 문의했더니 "NEW"로 넘겨주면 각 앱에서 처리하는 로직이 있다고 하여 원래대로 합치고자 합니다.

## 📝 Todo
- [x] Order entity의 sellrOrderStatus, customerOrderStatus -> orderStatus로 다시 합치기
- [x] 해당 수정에 따른 orderStatus enum, dto 수정
- [x] 해당 수정에 따른 코드 각 어플리케이션에서의 리팩터링
