### ISSUE TITLE
🛠️ [FIX] 문자열, 배열 중 nullable인 것들 수정

### ISSUE THREAD

**Issue by zer0who** [Team-JubJub/ZupZup_backend#263]
## 💬 Description
문자열, 배열 컬럼이 nullable인 것들 중 클라이언트에 null로 넘어갈 요소들에 대해 not null 처리를 수행합니다.

## 📝 Todo
- [x] Entity - Store의 category not null로 변경
- [x] Entity - Item의 imageURL not null로 변경(service 로직에서는 이미 기본값 처리가 되어있음)
- [x] Entity - Item의 salePrice not null로 변경(spring orm을 이용하면 int형은 자동으로 not null 처리, 그러나 코드에 가시성 부여 목적)
- [x] Entity - Item의 itemCount not null로 변경(spring orm을 이용하면 int형은 자동으로 not null 처리, 그러나 코드에 가시성 부여 목적)

-----------번외-----------
- [x] 신규 공지사항 등록 시 푸시알림 메시지 해요체로 변경
