### ISSUE TITLE
🛠️ [FIX] 사장님 앱 - 로그인 제어 로직 추가

### ISSUE THREAD

**Issue by zer0who** [Team-JubJub/ZupZup_backend#267]
## 💬 Description
사장님 앱에서 입점 취소 상태(회원 탈퇴를 진행 중)인 사장님의 로그인을 제어하는 로직을 추가합니다.

## 📝 Todo
- [x] 사장님 계정의 데이터 중 wantDeletion이 true인 경우, 회원탈퇴로 간주하여 로그인을 막는 로직 추가
- [x] 위 로직을 위한 예외 정의, advice 등록
- [x] 사장님 앱, 사용자 앱 advice와 exception 리팩터
