### ISSUE TITLE
[REFACTOR] 구조 정리

### ISSUE THREAD

**Issue by seasameoil** [Team-JubJub/ZupZup_backend#271]
## 💬 Description
spring-module-auth 추가 위한 구조 정리

## 📝 Todo
- [ ] 기존 Entity에 BaseEntity extends
- [ ] 인증 모듈 추가
  - [ ] 소셜 인증 및 자체 로그인 인증 패키지 기존 서비스에서 따로 분리
  - [ ] common 모듈에 Web과 App에 필수적인 내용들로만 정리 (파일 정리)
- [ ] REST Docs 적용

## ETC
refresh token 적용하려다 배보다 배꼽이 커진.,,,
