### ISSUE TITLE
🛠️ [Fix] Order entity에  builder 적용하기

### ISSUE THREAD

**Issue by zer0who** [Team-JubJub/ZupZup_backend#34]
## 💬 Description
Order dto -> entity 간 전환에 있어 메서드를 이용한 방법에서, Builder annotation을 사용한 생성자를 통한 전환을 하는 방법으로 바꾸는 작업을 수행합니다.

## 📝 Todo
- [x] Order Entity에 기본생성자 annotation 적용, access level - protected로 설정
- [x] 현재 전환이 이루어지는 곳에서 필요한 형태로의 생성자 overriding
- [x] 생성자에 Builder annotation 적용, 서비스에 적용해보기
