### ISSUE TITLE
🛠️ [Fix]Module dependency 정리, 수정

### ISSUE THREAD

**Issue by zer0who** [Team-JubJub/ZupZup_backend#38]
## 💬 Description
Module들 간의 dependency를 정리 및 수정합니다.

## 📝 Todo
- [x] root module build.gradle 정리 및 수정
- [x] :domain-module build.gradle 정리 및 수정
- [x] :application-module build.gradle 정리 및 수정
- [x] :application-module:application-common build.gradle 정리 및 수정
- [x] :application-module:seller build.gradle 정리 및 수정
- [x] :application-module:customer build.gradle 정리 및 수정
