### ISSUE TITLE
✨Google 로그인 설정(Google Cloud 계정, spring boot)

### ISSUE THREAD

**Issue by zer0who** [Team-JubJub/ZupZup_backend#64]
## 💬 Description
사용자 앱에서 사용될 소셜로그인 중 하나인  Google 로그인 기능을 구현하기 전 설정을 합니다.

## 📝 Todo
- [x] Google OAuth2 서비스 등록(일단 개인 계정으로)
- [x] 의존성 주입, application.yml 등 resource 파일 설정
- [x] 로그인 기능에 쓰일 테이블 Entity 설계
- [x] ERD 작성
