### ISSUE TITLE
👤 User 모델 정의 및 다이어그램 작성

### ISSUE THREAD

**Issue by zer0who** [Team-JubJub/ZupZup_backend#72]
## 💬 Description
저희 시스템 사용자의 model을 정의, 이를 문서화(테이블 작성)합니다.

## 📝 Todo
- [x] 유저 모델에 쓰일 필드 결정
- [x] 해당 유저 모델 테이블 작성
- [x] Spring boot User entity 수정 및 Dto 수정
