### ISSUE TITLE
📝 회원가입, 로그인, 로그아웃 기능 API 명세

### ISSUE THREAD

**Issue by zer0who** [Team-JubJub/ZupZup_backend#82]
## 💬 Description
회원가입, 로그인(자동 로그인, 재로그인), 로그아웃의 API명세를 swagger를 이용하여 작성합니다.

## 📝 Todo
- [x] 회원가입 명세
- [x] 로그인 - 자동 로그인 명세
- [x] 로그인 - 재로그인 명세
- [x] 로그아웃 명세
- [x] 명세 노션에 올리기(혹은 서버 띄워놓기)
