### ISSUE TITLE
🛠️ [FIX] Auth - 회원가입기능 리팩토링

### ISSUE THREAD

**Issue by zer0who** [Team-JubJub/ZupZup_backend#84]
## 💬 Description
Auth - 회원가입기능과 관련된 코드들의 리팩토링을 수행합니다.

## 📝 Todo
- [x] 토큰들의 전달 형태 쿠키 -> 헤더로 변경
    - [x] 회원가입 후 토큰 리턴 시 쿠키 -> 헤더로 변경
    - [x] 재로그인 후 토큰 리턴 시 쿠키 -> 헤더로 변경
    - [x] 인증 필요한 기능 요청 시 토큰 수령 방식 쿠키 -> 헤더로 변경
    - [x] refresh token validation 수행 시 액세스 토큰을 이용하도록 로직 수정
- [x] 회원가입 flow의 코드들 리팩토링
