### ISSUE TITLE
✨ 닉네임 중복 검사 구현

### ISSUE THREAD

**Issue by zer0who** [Team-JubJub/ZupZup_backend#87]
## 💬 Description
회원가입 시 닉네임 중복 검사를 하는 기능을 구현합니다.

## 📝 Todo
- [x] 닉네임 중복 검사 controller 구현
- [x] 닉네임 중복 검사 service 구현
- [x] API 명세 작성
