### ISSUE TITLE
✨ 회원탈퇴 기능 구현

### ISSUE THREAD

**Issue by zer0who** [Team-JubJub/ZupZup_backend#94]
## 💬 Description
회원 탈퇴 기능을 구현합니다. 
url: zupzuptest.com:8090/mobile/sign-up(method: DELETE)

## 📝 Todo
- [x] 회원탈퇴 기능 controller 구현
- [x] 회원탈퇴 기능 service 구현
- [x] 테스트(로컬)
- [x] 테스트 서버에 배포
