### ISSUE TITLE
🛠️ [FIX] 회원 관리 관련 URL 매핑 변경, 계정찾기 메서드, 닉네임 중복체크 파라미터 방식 변경

### ISSUE THREAD

**Issue by zer0who** [Team-JubJub/ZupZup_backend#95]
## 💬 Description
1. 회원가입, 탈퇴 등과 관련한 url을 하나로 묶기 위해 url 매핑을 변경합니다.(mobile/sign-up -> mobile/account)
2. 계정찾기의 메서드를 GET -> POST로 변경합니다.
3. 닉네임 중복체크 기능의 파라미터인 닉네임을 받는 방식을 request body -> path query로 변경합니다.

## 📝 Todo
- [x] 회원가입 url 변경
- [x] 계정찾기 메서드 변경
- [x] 닉네임 중복체크 파라미터 방식 변경
- [x] 명세 수정
